baseurl = "http://jad-b.github.io"
languageCode = "en-us"
title = "not without meaning"
theme = "curate"
editor = "vi"

disqusShortname = "not-without-meaning"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description="The education of a curious man."
