baseurl = "http://jad-b.github.io"
languageCode = "en-us"
title = "not without meaning"
editor = "vi"

disqusShortname = "not-without-meaning"

paginate = "10"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description="The education of a curious man."
