# theme.toml template for a Hugo theme

name = "Cure"
license = "MIT"
licenselink = "https://github.com/jad-b/cure/blob/master/LICENSE.md"
description = ""
homepage = "http://siteforthistheme.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
